table:
  source: adventureworks
  database: AdventureWorks2022
  source_schema: Sales
  source_table: SalesPerson
  target_name: salesperson
  enabled: true
  execution_order: 10

  load:
    type: full
    primary_key: [BusinessEntityID]
    fetch_size: 5000

  schema_drift:
    mode: strict
    alert_on_drift: true
    allowed_changes: [add_column]

  quality:
    expectations:
      - name: "person_id_not_null"
        constraint: "BusinessEntityID IS NOT NULL"
        action: fail
      - name: "valid_territory"
        constraint: "TerritoryID IS NOT NULL"
        action: warn

  silver:
    transformations:
      - type: add_column
        name: source_system
        expression: "'AdventureWorks'"
      - type: trim_strings
        columns: all
    scd_type: 2
    merge_keys: [BusinessEntityID]
