environment:
  name: dev
  catalog: daq_dev_dbx

  bronze:
    storage_path: "abfss://datalake@daqprod.dfs.core.windows.net/dev/bronze"
    schema: dev_bronze

  silver:
    catalog: daq_dev_dbx
    schema: dev_silver

  gold:
    catalog: daq_dev_dbx
    schema: dev_gold

  checkpoint_base: "abfss://datalake@daqprod.dfs.core.windows.net/dev/_checkpoints"

  cluster:
    num_workers: 1
    node_type_id: "Standard_D4s_v3"
    spark_version: "18.0.x-scala2.13"

  overrides:
    default_quality_action: warn
    streaming_trigger_interval: "60 seconds"
