environment:
  name: prod
  catalog: prod_catalog

  bronze:
    storage_path: "abfss://datalake@daqprod.dfs.core.windows.net/bronze"
    schema: bronze_raw

  silver:
    catalog: prod_catalog
    schema: silver_data

  gold:
    catalog: prod_catalog
    schema: gold_analytics

  control:
    catalog: prod_catalog
    schema: control

  checkpoint_base: "abfss://datalake@daqprod.dfs.core.windows.net/_checkpoints"

  cluster:
    num_workers: 4
    node_type_id: "Standard_D4s_v3"
    spark_version: "18.0.x-scala2.13"
    autoscale:
      min_workers: 2
      max_workers: 8

  overrides:
    default_quality_action: fail
    streaming_trigger_interval: "10 seconds"
